rollen:
  admin:
  tutor:

spring:
  flyway:
    schemas: chicken
    create-schemas: true
    url: jdbc:postgresql://localhost:5432/
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  datasource:
    url: jdbc:postgresql://localhost:5432/propra2
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}