spring:
  flyway:
    schemas: chicken
    create-schemas: true
    url: jdbc:postgresql://localhost:5432/
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  datasource:
    url: jdbc:postgresql://localhost:5432/chicken
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}