rollen:
  admin: winik100
  tutor:

spring:
  flyway:
    schemas: chicken
    create-schemas: true
    url: jdbc:postgresql://localhost:5432/
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  datasource:
    url: jdbc:postgresql://localhost:5432/propra2?currentSchema=chicken
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token