@startuml

skinparam monochrome true

[domain] <<..domain..>>
[services] <<..services..>>
[web] <<..infrastructure.web..>>
[persistenz] <<..infrastructure.persistenz..>>

[services]-->[domain]
[web]-->[services]
[persistenz]-->[services]

@enduml