version: "3.7"
services:
  db:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: propra2
      POSTGRES_PASSWORD: propra2
      POSTGRES_DB: propra2
